the-young-hana/theYoungHana-backend

.github/workflows/test.yml
src/main/java/hana/common/aspect/LoggerAspect.java
src/main/java/hana/common/dto/JwtToken.java
src/main/java/hana/common/entity/BaseEntity.java
src/main/java/hana/common/entity/BaseTimeEntity.java
src/main/java/hana/common/utils/JwtUtils.java
src/main/resources/application.yml
src/test/java/hana/ApplicationTests.java
src/test/java/hana/common/annotation/MethodInfoTest.java
src/test/java/hana/common/annotation/TypeInfoTest.java
src/test/java/hana/common/config/AppTestConfig.java
src/test/java/hana/common/config/MySQLTestConfig.java

프로젝트에 필요한 초기 설정들을 작업하기 위해 해당 PR를 생성하였습니다.
- [🔧 BaseEntity 추가](https://github.com/the-young-hana/theYoungHana-backend/pull/2/commits/fd7f4f23b0bbbc5a16bf73a7d0d330100503b4a0)
- [✅ MySQL testcontainer 리펙토링](https://github.com/the-young-hana/theYoungHana-backend/pull/2/commits/81c918a2a3444adfd6bf7881d1cb756e4f8e6525) 
- [🔧 JWT 설정 및 적용](https://github.com/the-young-hana/theYoungHana-backend/pull/2/commits/3bb6cb1a29e2195fb240a2ac64004de7641dbd07)
- [🔊 로그 출력 수정](https://github.com/the-young-hana/theYoungHana-backend/pull/2/commits/2e91de72a26ceafd35274cd0c0ca6c097d1f8325)
- [👷 배포 환경에서의 JWT 설정](https://github.com/the-young-hana/theYoungHana-backend/pull/2/commits/f534fe7813bfec4b26de54b7557c57ae7a5048f7)

chore: 프로젝트 초기 설정

---

src/main/java/hana/college/domain/Dept.java
src/main/java/hana/common/entity/BaseEntity.java
src/main/java/hana/common/entity/BaseTimeEntity.java
src/main/java/hana/event/domain/Event.java
src/main/java/hana/event/domain/EventPrize.java
src/main/java/hana/member/domain/StudentCard.java
src/main/java/hana/member/domain/StudentCardRepository.java
src/main/java/hana/story/domain/Story.java

프로젝트 도메인 설정

---

src/main/java/hana/knowledge/controller/KnowledgeController.java
src/main/java/hana/knowledge/service/KnowledgeService.java

금융상식 목록 조회 구현
금융상식 목록을 조회할 수 있는 API 구현

feat: 금융상식 목록 조회 구현

---

.github/workflows/pull_request_test.yml
src/main/java/hana/account/controller/TransactionController.java
src/main/java/hana/common/annotation/AuthenticatedMember.java
src/main/java/hana/common/config/JwtAuthenticationFilter.java
src/main/java/hana/common/config/JwtTokenProvider.java
src/main/java/hana/common/exception/CommonHttpCode.java
src/main/java/hana/common/exception/TokenExpiredException.java
src/main/java/hana/common/exception/TokenHasUnknownMemberException.java
src/main/java/hana/common/utils/JwtUtils.java
src/main/java/hana/common/vo/JwtToken.java
src/main/java/hana/common/vo/UserDetails.java
src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/domain/EventRepository.java
src/main/java/hana/event/service/EventService.java
src/main/java/hana/member/controller/MemberController.java
src/main/java/hana/member/domain/StudentRepository.java
src/main/java/hana/member/exception/MemberHttpCode.java
src/main/java/hana/member/exception/UnlistedMemberException.java
src/main/java/hana/member/service/MemberService.java
src/main/java/hana/story/controller/StoryController.java

feat: 이벤트 목록 조회 구현

---

build.gradle
src/main/java/hana/college/domain/DeptRepository.java
src/main/java/hana/reward/controller/RewardController.java
src/main/java/hana/reward/domain/Quiz.java
src/main/java/hana/reward/domain/QuizRepository.java
src/main/java/hana/reward/dto/RewardAnswerQuizResDto.java
src/main/java/hana/reward/service/RewardService.java

feat: 금융 퀴즈 api 구현

---

src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/college/domain/DeptRepository.java
src/main/java/hana/college/service/DeptService.java

fix: 송금 기능 가상계좌 입금 되게 수정 (#22)
- 가상 계좌번호로 본 계좌에 입금 가능하게 수정

fix: 송금 기능 가상계좌 입금 되게 수정 (#22)

---

build.gradle
lombok.config
src/main/java/hana/common/config/S3Config.java
src/main/java/hana/common/utils/ImageUtils.java
src/main/java/hana/reward/controller/RewardController.java
src/main/resources/application.yml

chore: Aws s3 연결

---

src/main/java/hana/account/domain/TransactionRepositoryCustom.java
src/main/java/hana/account/domain/TransactionRepositoryImpl.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/story/controller/StoryController.java
src/main/java/hana/story/domain/StoryCommentRepository.java
src/main/java/hana/story/domain/StoryLike.java
src/main/java/hana/story/domain/StoryLikeRepository.java
src/main/java/hana/story/domain/StoryRepository.java
src/main/java/hana/story/dto/StoriesReadResDto.java
src/main/java/hana/story/service/StoryCommentService.java
src/main/java/hana/story/service/StoryLikeService.java
src/main/java/hana/story/service/StoryService.java

스토리 목록 조회 구현
- 스토리 목록 조회 API 생성
- 스토리 좋아요 관련 파일(엔티티/리포/서비스) 추가

feat: 스토리 목록 조회 구현 (#26)

---

build.gradle
src/main/java/hana/common/config/JwtAuthenticationFilter.java
src/main/java/hana/common/utils/ImageUtils.java
src/main/java/hana/common/utils/JsonUtils.java
src/main/java/hana/common/utils/JwtUtils.java
src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/domain/Event.java
src/main/java/hana/event/domain/EventRepository.java
src/main/java/hana/event/dto/EventReadResDto.java
src/main/java/hana/event/exception/EventHttpCode.java
src/main/java/hana/event/exception/UnavailableEventException.java
src/main/java/hana/event/service/EventService.java
src/main/resources/application.yml
src/test/java/hana/common/config/AppTestConfig.java

feat: 이벤트 상세조회 구현

---

src/main/java/hana/account/domain/TransactionRepositoryCustom.java
src/main/java/hana/account/domain/TransactionRepositoryImpl.java
src/main/java/hana/account/dto/TransactionsByDateResDto.java
src/main/java/hana/account/dto/TransactionsReadResDto.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/common/config/QueryDSLConfig.java

거래 내역 조회 날짜로 그룹화
거래 내역 조회 날짜로 그룹화

:recycle: 거래 내역 조회 날짜로 그룹화 (#30)

---

build.gradle
src/main/java/hana/common/utils/RandomStringGenerator.java
src/main/java/hana/member/controller/StudentController.java
src/main/java/hana/member/domain/Student.java
src/main/java/hana/member/dto/StudentReadResDto.java
src/main/java/hana/member/exception/StudentHttpCode.java
src/main/java/hana/member/exception/StudentNotFoundException.java
src/main/java/hana/member/service/StudentService.java

학생증 정보 및 랜덤으로 생성되는 QR 코드를 조회할 수 있는 API를 개발

feat: 학생증 관련 API 구현

---

src/main/java/hana/account/domain/TransactionRepositoryCustom.java
src/main/java/hana/account/domain/TransactionRepositoryImpl.java
src/main/java/hana/account/dto/TransactionsByDateResDto.java
src/main/java/hana/account/dto/TransactionsReadResDto.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/common/config/QueryDSLConfig.java
src/main/java/hana/story/controller/StoryController.java
src/main/java/hana/story/domain/Story.java
src/main/java/hana/story/domain/TransactionDetail.java
src/main/java/hana/story/domain/TransactionDetailRepository.java
src/main/java/hana/story/dto/StoriesReadResDto.java
src/main/java/hana/story/dto/StoryCreateReqDto.java
src/main/java/hana/story/dto/StoryCreateResDto.java
src/main/java/hana/story/dto/StoryReadResDto.java
src/main/java/hana/story/dto/StoryRepresentativeCommentResDto.java
src/main/java/hana/story/service/StoryCommentService.java
src/main/java/hana/story/service/StoryService.java
src/main/java/hana/story/service/TransactionDetailService.java

feat: 스토리 상세 조회 및 작성 구현 (#26)

---

src/main/java/hana/common/utils/ImageUtils.java

s3등록 및 삭제 방식 변경
- 이미지 삭제 오류
- s3는 디렉토리 단위 삭제 불가능
- 이미지 등록 이름 변경
- aws자체의 캐싱 시스템으로, 동일한 이름이 등록되면 이전의 데이터를 불러서 가져옴
- 이미지의 이름을 인덱스로 하지 않고, 고유한 이름 부여

fix: s3등록 및 삭제 방식 변경 (#39)

---

src/main/java/hana/common/entity/BaseEntity.java
src/main/java/hana/story/controller/StoryController.java
src/main/java/hana/story/domain/Story.java
src/main/java/hana/story/domain/TransactionDetailRepository.java
src/main/java/hana/story/dto/StoryDeleteResDto.java
src/main/java/hana/story/dto/StoryUpdateReqDto.java
src/main/java/hana/story/dto/StoryUpdateResDto.java
src/main/java/hana/story/service/StoryService.java
src/main/java/hana/story/service/TransactionDetailService.java

스토리 수정/삭제 구현
- 스토리 수정 API 
- 스토리 삭제 API ( 논리적 삭제), 거래 내역은 물리적 삭제

feat: 스토리 수정/삭제 구현 (#26)

---

src/main/java/hana/story/controller/StoryController.java

병합 충돌 수정
스토리/스토리 댓글 컨트롤러 분리에 따른 병합 충돌 수정(spotlessApply_import삭제)

style: 병합 충돌 수정(spotlessApply)

---

src/main/java/hana/story/domain/StoryRepository.java
src/main/java/hana/story/service/StoryService.java

fix: 스토리 논리적 삭제에 따른 목록 리턴 기준 수정 (#43)

---

.github/workflows/pull_request_test.yml
src/test/java/hana/common/config/AppTestConfig.java

fix: 배포 오류 수정

---

src/main/java/hana/member/dto/StudentReadResDto.java
src/main/java/hana/member/service/StudentService.java

StudentReadResDto에서 학교 로고 이미지 추가

fix: StudentReadResDto 수정

---

src/main/java/hana/story/controller/StoryController.java
src/main/java/hana/story/domain/StoryLike.java
src/main/java/hana/story/domain/StoryLikeRepository.java
src/main/java/hana/story/dto/StoriesReadResDto.java
src/main/java/hana/story/dto/StoryCreateLikeResDto.java
src/main/java/hana/story/dto/StoryReadResDto.java
src/main/java/hana/story/service/StoryLikeService.java
src/main/java/hana/story/service/StoryService.java

스토리 좋아요 관련 API 구현
- 스토리 좋아요 토글 API 생성
- 스토리 정보 리턴 json에 좋아요 체크 여부 추가

feat: 스토리 좋아요 관련 API 구현 (#54)

---

src/main/java/hana/common/config/AuditAwareImpl.java
src/main/java/hana/common/config/JpaAuditConfig.java
src/main/java/hana/common/entity/BaseEntity.java

데이터베이스 생성자/수정자 자동화
데이터베이스 생성자/수정자 자동화

chore: 데이터베이스 생성자/수정자 자동화(#56)

---

src/main/java/hana/account/service/TransactionService.java

fix: 입금/출금자 이름 바뀌어서 나오는 버그 수정

---

src/main/java/hana/account/controller/TransactionController.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/common/exception/AccessDeniedCustomException.java
src/main/java/hana/common/exception/CommonHttpCode.java
src/main/java/hana/story/controller/StoryController.java
src/main/java/hana/story/service/StoryService.java

refactor: 인가 관련 예외처리 추가

---

.github/workflows/ci_and_cd.yml
.github/workflows/pull_request_test.yml
src/main/java/hana/common/config/FirebaseConfig.java
src/main/java/hana/common/config/SecurityConfig.java
src/main/java/hana/common/config/WebMvcConfig.java
src/main/java/hana/notification/controller/NotificationController.java

fix: cors 오류 해결

---

src/main/java/hana/common/repository/StoreQueryRepository.java
src/main/java/hana/story/controller/StoryCommentController.java
src/main/java/hana/story/domain/StoryComment.java
src/main/java/hana/story/domain/StoryCommentRepository.java
src/main/java/hana/story/dto/StoryCommentPaginationDto.java
src/main/java/hana/story/dto/StoryCreateCommentResDto.java
src/main/java/hana/story/dto/StoryUpdateCommentResDto.java
src/main/java/hana/story/service/StoryCommentService.java

feat: 스토리 댓글 관련 기능 구현

---

src/main/java/hana/college/domain/DeptRepository.java
src/main/java/hana/member/domain/Student.java
src/main/java/hana/member/domain/StudentRepository.java
src/main/java/hana/notification/controller/NotificationController.java
src/main/java/hana/reward/controller/RewardController.java
src/main/java/hana/reward/service/RewardService.java

feat: 리워드 관련 api 구현

---

src/main/java/hana/college/domain/DeptRepository.java
src/main/java/hana/common/config/FirebaseConfig.java
src/main/java/hana/member/domain/StudentRepository.java
src/main/java/hana/reward/controller/RewardController.java
src/main/java/hana/reward/service/RewardService.java

 style: 리워드 Spotless 적용

---

src/main/java/hana/college/domain/DeptRepository.java
src/main/java/hana/member/domain/StudentRepository.java
src/main/java/hana/reward/controller/RewardController.java
src/main/java/hana/reward/service/RewardService.java
src/main/java/hana/story/domain/Story.java
src/main/java/hana/story/service/StoryCommentService.java
src/main/java/hana/story/service/StoryLikeService.java
src/main/java/hana/story/service/StoryService.java

스토리 좋아요/댓글수 반정규화
- 스토리 테이블에 스토리 좋아요와 댓글 수 컬럼 추가

refactor: 스토리 좋아요/댓글수 반정규화 (#48)

---

src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/domain/EventRepository.java
src/main/java/hana/event/dto/EventCreateResDto.java
src/main/java/hana/event/dto/EventPushOnResDto.java
src/main/java/hana/event/dto/EventReadResDto.java
src/main/java/hana/event/dto/EventUpdateResDto.java
src/main/java/hana/event/exception/EventHttpCode.java
src/main/java/hana/event/exception/InProgressEventException.java
src/main/java/hana/event/service/EventService.java

feat: 이벤트 관련 API 구현

---

src/main/java/hana/common/Service/FCMService.java
src/main/java/hana/event/domain/EventPrizeRepository.java

:ambulance: FCM 예외처리 수정

---

src/main/java/hana/story/service/MatchCountScheduler.java

좋아요/댓글 수 정합성을 위한 스케줄러 작성
- 좋아요/댓글 수 반정규화에 따른 정합성 문제 발생 가능 -> 스케줄러를 통해 매일 0시 정합성 관리

feat: 좋아요/댓글 수 정합성을 위한 스케줄러 작성 (#48)

---

dockerfile

fix: 도커파일 수정 (리소스 파일 추가)

---

src/main/java/hana/common/Service/FCMService.java

fix: FCM 환경변수 로직 수정

---

src/main/java/hana/account/domain/TransactionRepositoryImpl.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/story/dto/StoriesReadResDto.java
src/main/java/hana/story/service/StoryService.java

스토리 목록 조회 리턴값 수정
- 스토리 목록 조회 리턴값에 거래 기간 및 총금액 추가

refactor: 스토리 목록 조회 리턴값 수정 (#48)

---

src/main/java/hana/common/converter/MultipartJackson2HttpMessageConverter.java
src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/domain/ScheduledEvent.java
src/main/java/hana/event/dto/EventCreateReqDto.java
src/main/java/hana/event/dto/EventReadResDto.java
src/main/java/hana/event/dto/EventUpdateReqDto.java

refactor: 이벤트 추가 DTO 수정 (이미지 추가)

---

src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/college/domain/DeptRepository.java
src/main/java/hana/college/service/DeptService.java

학과-계좌 n+1해결
- 학과 조회시 account fetch join

refact: 학과-계좌 n+1해결

---

docker-compose.yml
prometheus.yml

test: 프로메테우스, 그라파나 연동

---

src/main/java/hana/common/exception/CommonHttpCode.java
src/main/java/hana/common/exception/PageStartIndexException.java
src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/dto/EventReadResDto.java
src/main/java/hana/event/exception/DeptNotMatchException.java
src/main/java/hana/event/exception/EventAlreadyApplyException.java
src/main/java/hana/event/exception/EventDateInvalidException.java
src/main/java/hana/event/exception/EventDeleteOnlyOwnerException.java
src/main/java/hana/event/exception/EventEndInvalidException.java
src/main/java/hana/event/exception/EventFeeEndInvalidException.java
src/main/java/hana/event/exception/EventFeeStartInvalidException.java
src/main/java/hana/event/exception/EventHttpCode.java
src/main/java/hana/event/exception/EventStartInvalidException.java

refactor: 이벤트 예외처리 적용

---

src/main/java/hana/account/domain/TransactionRepositoryCustom.java
src/main/java/hana/account/domain/TransactionRepositoryImpl.java
src/main/java/hana/account/dto/TransactionsReadResDto.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/story/dto/StoryReadResDto.java
src/main/java/hana/story/service/StoryService.java

스토리 상세 조회 리턴값 날짜별로 리턴
- 스토리에 함께 첨부된 거래들 거래내역 전체 조회와 동일한 형식으로 변경

refactor: 스토리 상세 조회 리턴값 날짜별로 리턴 (#48)

---

src/main/java/hana/common/utils/ImageUtils.java
src/main/java/hana/event/controller/EventController.java

fix: 이벤트 수정 시 이미지 관련 오류 수정

---

src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/dto/EventReadResDto.java
src/main/java/hana/event/dto/EventsReadResDto.java

refactor: 이벤트 API에 최초생성일시 정보 추가

---

src/main/java/hana/knowledge/controller/KnowledgeController.java
src/main/java/hana/knowledge/dto/KnowledgePaginationDto.java
src/main/java/hana/knowledge/service/KnowledgeService.java

금융상식 목록 조회 페이지네이션 기능 추가

---

src/main/java/hana/account/controller/TransactionController.java
src/main/java/hana/account/dto/DeptAccountInfoDto.java
src/main/java/hana/account/dto/TransactionsReadResDto.java
src/main/java/hana/account/dto/TransactionsRemitCreateReqDto.java
src/main/java/hana/account/service/AccountService.java
src/main/java/hana/account/service/TransactionService.java

- 거래내역 조회 캐싱
- 거래 내역 상단 학과 정보 캐싱

refactor: 거래내역 조회 캐싱 (#48)

---

src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/domain/EventArrivalRepository.java
src/main/java/hana/event/domain/EventWinnerRepository.java
src/main/java/hana/event/domain/Fcfs.java
src/main/java/hana/event/domain/FcfsEvent.java
src/main/java/hana/event/dto/EventJoinResDto.java
src/main/java/hana/event/exception/AlreadyEndEventException.java
src/main/java/hana/event/exception/EventHttpCode.java
src/main/java/hana/event/exception/NotStartEventException.java
src/main/java/hana/event/service/EventService.java

feat: 이벤트 선착 구현

---

src/main/java/hana/account/controller/TransactionController.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/college/controller/DeptController.java
src/main/java/hana/college/dto/DeptInfoReadResDto.java
src/main/java/hana/college/service/DeptService.java

학과 계좌 정보 조회 API
- deptIdx로 학과 계좌 정보를 가져오는 API 생성

feat: 학과 계좌 정보 조회 API (#107)

---

src/main/java/hana/common/config/SecurityConfig.java
src/main/java/hana/event/controller/EventController.java

fix: 이벤트 수정 시 이미지 수정 불가능하도록 설정

---

src/main/java/hana/story/controller/StoryController.java
src/main/java/hana/story/service/StoryService.java

fix: 스토리 수정 시 이미지 수정 불가능하도록 설정

---

src/main/java/hana/common/config/SecurityConfig.java
src/main/resources/templates/index.html

fix: CORS 오류 수정

---

src/main/java/hana/story/controller/StoryController.java

refactor: 스토리 신청 Req 파람 대소문자 변경 (#115)

---

src/main/java/hana/knowledge/service/KnowledgeService.java
src/main/java/hana/story/service/StoryCommentService.java

스토리 목록, 금융상식 목록 조회 페이지네이션 기능 수정

---

src/main/java/hana/story/domain/Story.java

스토리 댓글/좋아요 수 null리턴 수정
- column default 0 설정

fix: 스토리 댓글/좋아요 수 null리턴 수정 (#123)

---

src/main/java/hana/story/service/StoryService.java

스토리 이미지 null일 경우 로직 변경
- 스토리 이미지 null값 확인
- 리스트 형식 파싱 함수 분리

fix: 스토리 이미지 null일 경우 로직 변경 (#125)

---

src/main/java/hana/account/domain/TransactionRepositoryImpl.java

fix: 거래내역 정렬 조건 추가(#127)

---

src/main/java/hana/common/config/SecurityConfig.java
src/main/java/hana/event/task/ScheduledEventTasks.java
src/main/java/hana/member/controller/MemberController.java
src/main/java/hana/member/dto/MemberCreateNoticeReqDto.java
src/main/java/hana/member/dto/MemberReadNoticesResDto.java

fix: 알림 목록 조회 DTO 수정

---

src/main/java/hana/account/controller/AccountController.java
src/main/java/hana/account/dto/AccountPwCheckReqDto.java
src/main/java/hana/account/dto/AccountPwCheckResDto.java
src/main/java/hana/account/service/AccountService.java

feat: 계좌 비밀번호 확인 API 생성 (#130)

---

src/main/java/hana/college/controller/DeptController.java

hotfix: 학과 정보 조회 임의 처리

---

src/main/java/hana/event/task/ScheduledEventTasks.java
src/main/java/hana/member/controller/MemberController.java
src/main/java/hana/member/dto/MemberLoginResDto.java
src/main/java/hana/member/dto/StudentLoginResDto.java
src/main/java/hana/member/service/StudentService.java

feat: 간편로그인과 영하나 접속 API 분리

---

src/main/java/hana/member/dto/StudentReadResDto.java
src/main/java/hana/member/service/StudentService.java
src/main/java/hana/story/service/StoryService.java

학생증 조회 API DeptIdx, StudentIdx, MemberIdx, isAdmin 추가

---

src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/exception/EventCreateOnlyAdminException.java
src/main/java/hana/event/exception/EventDeleteOnlyAdminException.java
src/main/java/hana/event/exception/EventDeleteOnlyOwnerException.java
src/main/java/hana/event/exception/EventHttpCode.java
src/main/java/hana/event/exception/EventUpdateOnlyAdminException.java
src/main/java/hana/member/domain/Student.java
src/main/java/hana/member/service/StudentService.java

refactor: 이벤트 생성/수정/삭제 권한 추가

---

src/main/java/hana/account/controller/TransactionController.java
src/main/java/hana/account/dto/TransactionsRemitCreateReqDto.java
src/main/java/hana/account/service/AccountService.java
src/main/java/hana/account/service/TransactionService.java
src/main/java/hana/college/controller/DeptController.java
src/main/java/hana/college/service/DeptService.java

fix: 학과 관련 입출금 로직 변경(#132)

---

src/main/java/hana/member/controller/MemberController.java
src/main/java/hana/member/dto/StudentLoginResDto.java

fix: 더영하나 접속 DTO 수정

---

src/main/java/hana/member/domain/Student.java
src/main/java/hana/story/domain/StoryCommentRepository.java
src/main/java/hana/story/dto/StoryCommentPaginationDto.java
src/main/java/hana/story/dto/StoryReadCommentsResDto.java
src/main/java/hana/story/service/StoryCommentService.java

refactor: 스토리 댓글 목록 조회 API 수정

---

src/main/java/hana/reward/service/RewardService.java

fix: 타임존 한국으로 변경

---

src/main/java/hana/event/controller/EventController.java
src/main/java/hana/event/dto/EventCreateReqDto.java
src/main/java/hana/event/dto/EventUpdateReqDto.java

fix: 이벤트 API DTO LocalDateTime -> String

---

src/main/java/hana/story/service/StoryService.java

스토리 이미지 확장자 png, jpg 모두 가능하게 변경

fix: 스토리 이미지 확장자 png, jpg 모두 가능하게 변경 (#151)

---

src/main/java/hana/event/controller/EventController.java

fix: 이벤트 DTO에 DateTimeFormatter 적용

---

src/main/java/hana/reward/service/RewardService.java

hotfix: 타임스탬프 로그(#146)

---

src/main/java/hana/reward/domain/RewardHistoryRepository.java
src/main/java/hana/reward/service/RewardService.java

hotfix: 타임스탬프 로그 수정 (#146)

---

src/main/java/hana/reward/domain/RewardHistoryRepository.java
src/main/java/hana/reward/service/RewardService.java

hotfix: 쿼리문 수정

---

src/main/java/hana/story/service/MatchCountScheduler.java

refactor: 삭제된 글 스케줄러 안 돌게 수정

---

src/main/java/hana/common/config/JwtAuthenticationFilter.java
src/main/java/hana/common/config/SecurityConfig.java
src/main/java/hana/member/controller/MemberController.java
src/main/java/hana/member/domain/MemberToken.java
src/main/java/hana/member/domain/MemberTokenRepository.java
src/main/java/hana/member/service/MemberTokenService.java

refactor: 로그인 시점에 캐싱
